import tkinter
import pymysql
from tkinter import*
from tkinter import ttk
from tkinter import messagebox
def admintableupdate() :
    t=tkinter.Tk()
    t.geometry('1300x800')
    d=Canvas(t,height=1500,width=1500,bg='Green')
    d.place(x=0,y=0)
    head=Label(t,text='Admin Table Update',font=('arial',30,"italic underline"),fg='black',bg='light green')
    head.place(x=450,y=10)
    def filldata() :
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        lt=[]
        sql="select adminid from admintable"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            lt.append(res[0])
        e1['values']=lt
    def updatedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=e4.get()
        sql = "update admintable set name='%s',password='%s',emailid='%s' where adminid=%d"%(xb,xc,xd,xa)
        cur.execute(sql)
        db.commit()
        mes.config(fg='black')
        mes.config(text='Updated :)')
        db.close()
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
    def finddata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        xa=int(e1.get())
        sql="select name,password,emailid from admintable where adminid=%d" %(xa)
        cur.execute(sql)
        data=cur.fetchone()
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e2.insert(0,str(data[0]))
        e3.insert(0,str(data[1]))
        e4.insert(0,str(data[1]))
        db.close()
    def close():
        t.destroy()
    mes=Label(t,text='',font=('arial',64),bg='green',width=10,height=2)
    mes.place(x=685,y=170)
    a=Label(t,text='Admin-ID',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    a.place(x=320,y=100)
    e1=ttk.Combobox(t) 
    filldata()
    e1.place(x=550,y=110)
    b1=Button(t,text='Find',font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9,bd=10,command=finddata)
    b1.place(x=750,y=100)
    b=Label(t,text='Name',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    b.place(x=320,y=190)
    e2=Entry(t,width=20,bd=15)
    e2.place(x=550,y=190)
    c=Label(t,text='Password',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    c.place(x=320,y=280)
    e3=Entry(t,width=20,bd=15)
    e3.place(x=550,y=280)
    d=Label(t,text='Email-Id',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    d.place(x=320,y=370)
    e4=Entry(t,width=20,bd=15)
    e4.place(x=550,y=370)
    b1=Button(t,text='Update',font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9,bd=10,command=updatedata)
    b1.place(x=750,y=390)
    b2=Button(t,text='Close',font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9,bd=10,command=close)
    b2.place(x=750,y=530)
    t.mainloop()