import tkinter
import pymysql
from tkinter import*
from tkinter import ttk
from tkinter import messagebox
def departmentupdate() :
    t=tkinter.Tk()
    t.geometry('1300x750')
    d=Canvas(t,height=1500,width=1500,bg='Green')
    d.place(x=0,y=0)
    head=Label(t,text='Department Update',font=('arial',30,"italic underline"),fg='black',bg='light green')
    head.place(x=450,y=10)
    def filldata() :
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        lt=[]
        sql="select deptid from department"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            lt.append(res[0])
        e1['values']=lt
    def updatedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=int(e4.get())
        xe=e5.get()
        sql = "update department set dname='%s',hodname='%s',hodemailid=%d,specailremarks='%s' where deptid=%d"%(xb,xc,xd,xe,xa)
        cur.execute(sql)
        db.commit()
        mes.config(fg='black')
        mes.config(text='Updated :)')
        db.close()
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
    def finddata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        xa=int(e1.get())
        sql="select dname,hodname,hodemailid,specailremarks from department where deptid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e2.insert(0,str(data[0]))
        e3.insert(0,str(data[1]))
        e4.insert(0,str(data[2]))
        e5.insert(0,data[3])
        db.close()
    def close():
        t.destroy()
    mes=Label(t,text='',font=('arial',64),bg='green',width=10,height=2)
    mes.place(x=685,y=170)
    a=Label(t,text='Dept-ID',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    a.place(x=350,y=102)
    e1=ttk.Combobox(t) 
    filldata()
    e1.place(x=530,y=110)
    b1=Button(t,text='Find',font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9,command=finddata)
    b1.place(x=750,y=100)
    b=Label(t,text='DName',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    b.place(x=350,y=214)
    e2=Entry(t,width=20,bd=15)
    e2.place(x=530,y=214)
    c=Label(t,text='Hodname',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    c.place(x=315,y=326)
    e3=Entry(t,width=20,bd=15)
    e3.place(x=530,y=326)
    d=Label(t,text='Hodemail-Id',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    d.place(x=270,y=438)
    e4=Entry(t,width=20,bd=15)
    e4.place(x=530,y=438)
    z=Label(t,text='Special Remark',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    z.place(x=220,y=550)
    e5=Entry(t,width=20,bd=15)
    e5.place(x=530,y=550)
    b1=Button(t,text='Update',font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9,command=updatedata)
    b1.place(x=750,y=390)
    b2=Button(t,text='Close',font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9,command=close)
    b2.place(x=750,y=530)
    t.mainloop()