import tkinter
import pymysql
from tkinter import*
from tkinter import ttk
from tkinter import messagebox
def staffupdate() :
    t=tkinter.Tk()
    t.geometry('1300x750')
    d=Canvas(t,height=1500,width=1500,bg='Green')
    d.place(x=0,y=0)
    head=Label(t,text='Staff Update',font=('arial',30,"italic underline"),fg='black',bg='light green')
    head.place(x=500,y=10)
    def filldata() :
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        lt=[]
        sql="select staffid from staff"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            lt.append(res[0])
        e1['values']=lt
    def updatedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=e4.get()
        xe=e5.get()
        xf=int(e6.get())
        sql = "update staff set sname='%s',address='%s',phone='%s',emailid='%s',deptid=%d where staffid=%d"%(xb,xc,xd,xe,xf,xa)
        cur.execute(sql)
        db.commit()
        mes.config(fg='black')
        mes.config(text='Updated :)')
        db.close()
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
    def finddata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='epcs')
        cur=db.cursor()
        xa=int(e1.get())
        sql="select sname,address,phone,emailid,deptid from staff where staffid=%d" %(xa)
        cur.execute(sql)
        data=cur.fetchone()
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        e2.insert(0,str(data[0]))
        e3.insert(0,str(data[1]))
        e4.insert(0,str(data[2]))
        e5.insert(0,str(data[3]))
        e6.insert(0,data[4])
        db.close()
    def close():
            t.destroy()
    mes=Label(t,text='',font=('arial',64),bg='green',width=10,height=2)
    mes.place(x=685,y=170)
    a=Label(t,text='Staff-Id',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    a.place(x=350,y=100)
    e1=ttk.Combobox(t) 
    filldata()
    e1.place(x=550,y=110)
    b1=Button(t,text='Find',command=finddata,font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9)
    b1.place(x=750,y=100)
    b=Label(t,text='SName',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    b.place(x=350,y=190)
    e2=Entry(t,width=20,bd=15)
    e2.place(x=550,y=190)
    c=Label(t,text='Address',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    c.place(x=350,y=280)
    e3=Entry(t,width=20,bd=15)
    e3.place(x=550,y=280)
    d=Label(t,text='Phone',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    d.place(x=350,y=370)
    e4=Entry(t,width=20,bd=15)
    e4.place(x=550,y=370)
    z=Label(t,text='Email-I',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    z.place(x=350,y=460)
    e5=Entry(t,width=20,bd=15)
    e5.place(x=550,y=460)
    y=Label(t,text='Dept-Id',font=('georgia',25,"italic underline"),fg='black',bg='light green')
    y.place(x=350,y=550)
    e6=Entry(t,width=20,bd=15)
    e6.place(x=550,y=550)
    b2=Button(t,text='Update',command=updatedata,font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9)
    b2.place(x=750,y=380)
    b2=Button(t,text='Close',command=close,font=('georgia',25,"italic underline"),fg='black',bg='light green',width=9)
    b2.place(x=750,y=530)
    t.mainloop()